services:
  db:
    image: postgres:16-alpine
    container_name: proyect
    restart: always
    environment:
      POSTGRES_USER: user_pos
      POSTGRES_PASSWORD: pos_password_2026
      POSTGRES_DB: pos_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
